Check for entire catalog compilation, not just changed files

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -59,6 +59,16 @@ do
 done
 echo ""
 
+echo "### Checking if the catalog compiles"
+puppet apply --noop manifests/site.pp
+if [[ $? -ne 0 ]]
+then
+    echo "ERROR: puppet catalog compilation failed"
+    syntax_is_bad=1
+else
+    echo "OK: $file looks valid"
+fi
+
 echo "### Checking if ruby template syntax is valid ###"
 for file in `git diff --name-only --cached | grep -E '\.(erb)'`
 do
